[package]
name = "rillrate"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.6"
failure = "0.1.5"
hyper = "0.12.31"

[dependencies.futures]
version = "0.1.28"

[dependencies.futures3]
package = "futures-preview"
version = "=0.3.0-alpha.16"
features = ["async-await", "nightly", "compat"]
