[package]
name = "facade-protocol"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
bigdecimal = { version = "0.1.0", features = ["serde"] }
serde = "1.0.94"
serde_derive = "1.0.94"
